INSERT INTO data (major, 
                  submajor,
                    minor,
                      subminor, 
                      grade, 
                      file_formats,
                        type, 
                        source_description, 
                        place_city,
                          year, 
                          publisher,
                            path, 
                            collection, 
                            collection_type, 
soi_toposheet_no,
 grade1, 
data_resolution, 
ownership, 
is_processed, 
short_descr, 
descr, 
img_service, 
img_dw, 
map_service, 
map_dw,
 publish_on, 
thumbnail,
 source, 
 created_id,
   created_date,
     modified_id, 
     modified_date,
     deleted_id,
     deleted_date )
VALUES(
    'Geography', 
    'Urban Development',
    'Delhi', 
    'General Information', 
    'A', 
    'PDF',
    'Geospatial', 
    '', 
    'Delhi', 
    '2023',
    'Government of Delhi', 
    '/path/to/delhi_general_info', 
    'General Information Collection', 
    'City Information', 
    'N/A', 
    'A',
    'Not applicable',
    'Government',
    'Yes',
    'General information about Delhi, India', 
    'This dataset provides an overview of Delhi, including its history, demographics, and key landmarks. It aims to offer a comprehensive understanding of the city and its significance in the Indian context.',
    'Delhi is the capital city of India and one of the largest metropolitan areas in the country. It is known for its rich history, diverse culture, and architectural landmarks such as the Red Fort, Qutub Minar, and India Gate. Delhi serves as a major political, commercial, and cultural center, attracting visitors from around the world.', 
    'https://example.com/img_dw', 
    'https://example.com/map_service', 
    'https://example.com/map_dw', 
    'https://example.com/map_service', 
    'https://example.com/map_dw', 
    'Google Earth',
    'https://example.com/thumbnail',
    NULL,
    'JohnDoe',
    '2023-06-29',
    'JohnDoe',
    '2023-06-29'
);