# Generated by Django 4.2.2 on 2023-07-31 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigIntegerField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('major', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('submajor', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('minor', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('subminor', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('grade', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('file_formats', models.CharField(default='null', max_length=512, null=True)),
                ('type', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('source_description', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('place_city', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('year', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('publisher', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('path', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('collection', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('collection_type', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('soi_toposheet_no', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('grade1', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('data_resolution', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('ownership', models.CharField(default='null', max_length=512, null=True)),
                ('is_processed', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('short_descr', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('descr', models.TextField(blank=True, default='null', null=True)),
                ('img_service', models.TextField(blank=True, default='null', null=True)),
                ('img_dw', models.TextField(blank=True, default='null', null=True)),
                ('map_service', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('map_dw', models.TextField(blank=True, default='null', null=True)),
                ('publish_on', models.TextField(blank=True, default='null', null=True)),
                ('thumbnail', models.TextField(blank=True, default='null', null=True)),
                ('source', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('created_id', models.CharField(blank=True, default='null', max_length=512, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_id', models.CharField(blank=True, default='null', max_length=50, null=True)),
                ('deleted_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('down_date', models.DateField(auto_now_add=True)),
                ('image_type', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('image_name', models.EmailField(blank=True, default='null', max_length=250, null=True)),
                ('image_url', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('country', models.CharField(blank=True, default='null', max_length=250, null=True)),
                ('email_id', models.CharField(default='null', max_length=100, null=True)),
            ],
        ),
    ]
