# Generated by Django 4.2.2 on 2023-07-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchbar.data'),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='image_name',
            field=models.CharField(blank=True, default='null', max_length=250, null=True),
        ),
    ]
