# Generated by Django 5.0.1 on 2024-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchbar', '0002_downloads_data_alter_downloads_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='data',
        ),
        migrations.AddField(
            model_name='downloads',
            name='items_id',
            field=models.CharField(blank=True, default='null', max_length=250, null=True),
        ),
    ]
